### ISSUE TITLE
Template not working

### ISSUE THREAD

**Issue by morukutsu** [mantinedev/mantine-next-template#1]
Hi, 
I was testing mantine using this nextjs template and went into some errors.
"TypeError: (0 , jss__WEBPACK_IMPORTED_MODULE_6__.createGenerateId) is not a function"

In this file:
https://github.com/mantinedev/mantine-next-template/blob/e81c7114d165450e2bfb5043c16e18de2216089c/pages/_app.tsx#L7

The problem was solved by importing react-jss instead of jss here.
I don't know much about the details yet, but I believe it's a typo!

Thanks

**Comment by rtivital** [comment]
Thanks for reporting, the issue was fixed
