### ISSUE TITLE
SSR breaks with next v12.1.6

### ISSUE THREAD

**Issue by PegasisForever** [mantinedev/mantine-next-template#15]
To reproduce:

1. Change nextjs version to 12.1.6 (12.1.5 still works)
2. `yarn export`
3. Inspect the generated `index.html` file, the `style` tag is empty.

(I spent SO MUCH time to track this bug down 😭)

**Comment by rtivital** [comment]
It is issue with Next.js, not Mantine, as far as I know it will be resolved in 12.1.7
