### ISSUE TITLE
nextjs 13

### ISSUE THREAD

**Issue by meirpertzz** [mantinedev/mantine-next-template#26]
Hi, you’re planning to create some beta starter-template for nextJS 13?
If not, I would like some instructions.

Thank you very much. 
love and appreciate your work.

**Comment by rtivital** [comment]
You can find example in this branch – https://github.com/mantinedev/mantine-next-template/tree/next-13-app

**Comment by meirpertzz** [comment]
> You can find example in this branch – https://github.com/mantinedev/mantine-next-template/tree/next-13-app

thank you very much!

**Comment by shinebayar-g** [comment]
Hi @rtivital , thank you very much for the example. Is there any chance Mantine team could make next.js 13 app dir example into the official docs?
