### ISSUE TITLE
Template points to old doc link

### ISSUE THREAD

**Issue by unknown** [mantinedev/mantine-next-template#3]
The [`Change theme` button](https://github.com/mantinedev/mantine-next-template/blob/e04efd6fa291558908117138194f05e2da2457e1/pages/index.tsx#L76) points to a now deleted page in the docs. `theming` context is no longer supported, and the button should should point to [this](https://mantine.dev/theming/mantine-provider/) doc link instead.

**Comment by rtivital** [comment]
Thanks for reporting, I've fixed the issue
