### ISSUE TITLE
Add official Next.js example with Mantine in Next.js repo

### ISSUE THREAD

**Issue by nexxeln** [mantinedev/mantine-next-template#8]
Why not add a template to the official [examples directory of Next.js](https://github.com/vercel/next.js/tree/main/examples)?

That way people can bootstrap a Next.js + Mantine Project with ```npx create-next-app -e with-mantine```

**Comment by rtivital** [comment]
Because it will be much harder to update as it will require raising PR in Next.js main repo, it will not be synchronized with Mantine releases cycle.

**Comment by nexxeln** [comment]
Makes sense, thank you for all the amazing work!
