### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by carlossgv** [mantinedev/mantine-next-template#9]
When trying to install the dependencies from the template I had issues with `react` and `modulz/radix-icons`. React is in version 18.0.0 and Modulz works with React 16 or 17, I couldn't check all of the dependencies but for example Storybook also used React 16 or 17.

**Comment by rtivital** [comment]
This template uses yarn, dependencies can be installed correctly and everything works fine. You can downgrade react to 17 if it is an issue for you.

**Comment by Maetes** [comment]
It depends. The used dependency for the icons is old i think. I issue a pull request to overwrite this, but its just a icon lib, so... but I like to be up to date. 

@carlossgv you can simply fix the issue with replacing the import in the package.json but you will face another one with storybook which is actually not ready for react 18 (still in beta). I recommend you to install with yarn or npm with "--legacy-peer-deps" and you should good to go.
